
"""
    异常: 不正常
        程序在执行的过程中,发生了不正常的事件,使程序不能继续执行

        不正常事件:
            python解释器, 发现了一个错误, 抛出了一个异常对象, 打断了程序的执行

"""
# 获取键盘输入一个整数, 让这个整数+10, 然后输出
##num = input("请输入一个整数")  # 1,str 2,阻塞式
##try:
##
##    num = int(num)
##    res = num + 10
##    print(res)
##except ValueError as e:
##    print('之错误:',e,type(e))
##else:
##    print('ok')
##finally:
##    print('dfsgf')
##class MException(Exception):
##    def __init__(self
##                 ,input_len,at_least):
##        self.input_len = input_len
##        self.at_least = at_least
##num = input('请输入8位以上的密码')
##
##try:
##    input_len = len(num)
##    if input_len < 8:
##        e = MException(input_len,8)
##        raise e
##except MException as e:
##    print('Exception错误:',e,type(e))
##else:
##    print('密码正确')
##finally:
##    print('ok')
def foo():
    
    





